# Generated by Django 5.0.2 on 2024-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=240)),
                ('admin_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=240)),
                ('date', models.DateField()),
                ('holidayName', models.CharField(max_length=240)),
            ],
        ),
    ]
