# Generated by Django 5.0.2 on 2024-03-11 18:49

import holiday.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(validators=[holiday.models.present_or_future_date]),
        ),
    ]
